export const DEFAULT_INCREASE_PERCENTAGE = "10";
export const DEFAULT_RECOVERY_WEEK_PERCENTAGE = "80";
export const DEFAULT_RECOVERY_WEEK_FREQUENCY = "3";
export const DEFAULT_LONG_RUN_PERCENTAGE = "30";
